# Generated by Django 3.0 on 2021-03-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_history',
            old_name='quiz_id',
            new_name='test_id',
        ),
    ]
