# Generated by Django 3.0 on 2021-03-03 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0016_auto_20210303_0857'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentDashboard', '0002_auto_20210303_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_history',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPanel.Test'),
        ),
        migrations.AlterField(
            model_name='exam_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
