# Generated by Django 3.0 on 2021-03-03 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentDashboard', '0003_auto_20210303_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_history',
            name='date',
        ),
        migrations.AddField(
            model_name='exam_history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam_history',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
