# Generated by Django 3.1.2 on 2021-03-12 05:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentDashboard', '0004_auto_20210303_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam_history',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='exam_history',
            name='selected_ans',
            field=jsonfield.fields.JSONField(),
        ),
    ]
