# Generated by Django 3.1.2 on 2021-03-16 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0020_auto_20210312_1637'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentDashboard', '0005_auto_20210312_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left', models.CharField(max_length=10, null=True)),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPanel.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
