# Generated by Django 3.1.2 on 2021-03-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDashboard', '0006_time_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_history',
            name='is_test_given',
            field=models.BooleanField(default=False),
        ),
    ]
