# Generated by Django 3.1.2 on 2020-12-08 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='createdOn',
            field=models.DateField(default=datetime.date.today, verbose_name='Posted on'),
        ),
    ]
