# Generated by Django 3.1.2 on 2020-12-09 06:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_test_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 11, 45, 49, 802240), verbose_name='Posted on'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPanel.test')),
            ],
        ),
    ]
