# Generated by Django 3.1.2 on 2020-12-24 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_auto_20201224_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty_level',
        ),
        migrations.AlterField(
            model_name='test',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2020, 12, 24, 15, 11, 47, 604581), verbose_name='Posted on'),
        ),
    ]
