# Generated by Django 3.1.2 on 2020-12-25 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_auto_20201224_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AlterField(
            model_name='test',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2020, 12, 25, 14, 44, 45, 181807), verbose_name='Posted on'),
        ),
    ]
