# Generated by Django 3.0 on 2020-12-25 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_auto_20201225_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2020, 12, 25, 16, 39, 42, 46936), verbose_name='Posted on'),
        ),
    ]
