# Generated by Django 3.0 on 2020-12-25 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0010_auto_20201225_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2020, 12, 25, 17, 48, 27, 604693), verbose_name='Posted on'),
        ),
    ]
