# Generated by Django 3.0 on 2020-12-25 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0012_auto_20201225_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2020, 12, 25, 19, 14, 1, 547150), verbose_name='Posted on'),
        ),
    ]
