# Generated by Django 3.0 on 2020-12-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0014_auto_20201225_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='dateTime',
            field=models.DateTimeField(max_length=100),
        ),
    ]
