# Generated by Django 3.0 on 2021-03-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0015_auto_20201226_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-createdOn']},
        ),
    ]
