# Generated by Django 3.1.2 on 2021-03-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0017_question_que_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='que_type',
        ),
        migrations.AddField(
            model_name='question',
            name='descriptive_answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_objective',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
