# Generated by Django 3.1.2 on 2021-03-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0018_auto_20210312_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_objective',
            field=models.BooleanField(null=True),
        ),
    ]
