# Generated by Django 3.0.3 on 2021-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0020_auto_20210312_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='branch_field',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='year_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
