# Generated by Django 3.1.7 on 2021-03-24 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0022_auto_20210324_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 20, 0, 4, 986427)),
            preserve_default=False,
        ),
    ]
