# Generated by Django 3.1.7 on 2021-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0023_test_test_end_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_end_datetime',
        ),
        migrations.AddField(
            model_name='test',
            name='test_end_hours',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
