# Generated by Django 3.1.2 on 2020-12-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201123_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
