# Generated by Django 3.1.2 on 2020-12-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userregistration_isteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='college_name',
            field=models.CharField(default='SaifCollege', max_length=200),
        ),
    ]
