# Generated by Django 3.0.3 on 2021-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userregistration_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
