# Generated by Django 3.0.3 on 2021-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210324_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='college_name',
            field=models.CharField(max_length=200),
        ),
    ]
