# Generated by Django 3.1.7 on 2021-03-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210324_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
