# Generated by Django 3.0.3 on 2021-03-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210324_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='prn_number',
            field=models.IntegerField(null=True),
        ),
    ]
