# Generated by Django 3.0.3 on 2021-03-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userregistration_prn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='prn_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
