# Generated by Django 3.1.7 on 2021-03-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210325_1112'),
        ('accounts', '0008_auto_20210324_1803'),
    ]

    operations = [
    ]
